[package]
name = "hive-ml"
version = "0.1.0"
edition = "2021"

[dependencies]
tch = "0.19.0"
hive-engine = { path = "../hive-engine" }
rand = { version="*", features=["small_rng"] }
chrono = "*"
opentelemetry = "*"
opentelemetry_sdk = "*"
opentelemetry-otlp = "*"